### ISSUE TITLE
Getting TLS error

### ISSUE THREAD

**Issue by krispassa** [Emrals/Fuse#77]
Hi,
I keep getting  this error Stripe no longer supports API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2 or later. You can learn more about this at https://stripe.com/blog/upgrading-tls. I am a  bit new to this...wonder how i fix this problem.

**Comment by seanauriti** [comment]
This only happens on Fuse and not when on iOS or Android.  You can test in preview mode. I think this is a Fuse issue.  Thanks for reporting it.

**Comment by krispassa** [comment]
I did test preview on device and it console log this message {"card[number]":"4242424242424242","card[exp_month]":"05","card[exp_year]":"20","card[cvc]":"200"}
{"object":"list","data":[],"has_more":false,"url":"/v1/charges"}

there is no any api request shown in log page on Stripe dashboard.

**Comment by seanauriti** [comment]
do you have a valid stripe token?

**Comment by krispassa** [comment]
Apparently it starts working after I delete bundle file and uno clean. One question though, in some stripe docs it says we have to use this url https://api-tls12.stripe.com/v1/tokens...what's that mean?

**Comment by seanauriti** [comment]
oh, maybe that will fix this error,  want to give it a try?  Feel free to send a PR if you can get it working in Fuse with that.

**Comment by seanauriti** [comment]
reopening to see if there is a potential fix, maybe using api-tls12 will fix this error...

**Comment by krispassa** [comment]
Your method worked. Talked to Stripe support they told me that that's just a test url because they are moving to tls 1.2 if requesting from third party. You can close this issue now. Thank you for you time :)

**Comment by seanauriti** [comment]
ok thanks

**Comment by seanauriti** [comment]
Did you figure out a way to create the charge through Fusetools or do we still need to do it through mobile?
